version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        #TaskDefinition: "arn:aws:ecs:eu-west-3:324215794169:task-definition/api-counselor-task-definition:1"
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "java_training_docker_registry"
          ContainerPort: 8080