version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  build:
    commands:
      - echo "Building application..."
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  post_build:
    commands:
      - echo "Running tests..."
      - mvn test
artifacts:
  files:
    - target/*.jar
