version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto-17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker build -t java_training_docker_registry:latest .
      - docker tag java_training_docker_registry 176497889442.dkr.ecr.eu-west-3.amazonaws.com/java_training_docker_registry
      - docker push 176497889442.dkr.ecr.eu-west-3.amazonaws.com/java_training_docker_registry
      - echo Writing image definitions file...
artifacts:
  files:
    - target/*.jar
    - imagedefinitions.json
