version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker build -t java_training_docker_registry:latest .
      - docker tag $ECR_NAME  $ECR_URL
      - docker push $ECR_URL
      - echo Writing image definitions file....

