version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install
      
  pre_build:
    commands:
      - echo Running tests...
      - mvn test

  build:
    commands:
      - echo Building Docker image...
      - docker build -t counselor_app_api:latest .

  post_build:
    commands:
      - echo Pushing Docker image to registry...
      - $(aws ecr get-login --no-include-email --region <region>)
      - docker push <docker-image-name>:<tag>

artifacts:
  files:
    - '**/*'
  discard-paths: yes
